/** @type {import("prettier").Config} */
const config = {
  trailingComma: 'es5',
  tabWidth: 2,
  semi: true,
  singleQuote: true,
  jsxSingleQuote: false,
  printWidth: 100,
  bracketSpacing: true,
  endOfLine: 'auto',
  bracketSameLine: false,
  arrowParens: 'always',
  importOrder: [
    '^(react/(.*)$)|^(react$)',
    '^(next/(.*)$)|^(next$)',
    '<THIRD_PARTY_MODULES>',
    '',
    '^@supabase/(.*)$',
    '',
    '^@/components/(.*)$',
    '^@/components/ui/(.*)$',
    '^@/styles/(.*)$',
    '^@/app/(.*)$',
    '',
    '^@/types$',
    '^@/types/(.*)$',
    '^@/config$',
    '',
    '^@/hooks/(.*)$',
    '^@/lib/(.*)$',
    '^@/app/actions/(.*)$',
    '^./actions',
    '',
    '^@/utils/(.*)$',
    '^@/constants/(.*)$',
    '',
    '^[./]',
  ],
  importOrderSeparation: true,
  importOrderSortSpecifiers: true,
  importOrderParserPlugins: ['typescript', 'jsx', 'decorators-legacy'],
  importOrderMergeDuplicateImports: true,
  importOrderCombineTypeAndValueImports: true,
  plugins: [
    '@ianvs/prettier-plugin-sort-imports',
    'prettier-plugin-tailwindcss',
  ],
};

export default config;
